# Generated by Django 4.2.3 on 2024-01-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_passwordchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChange',
        ),
    ]
