# Generated by Django 4.2.3 on 2024-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_additional_info_course_amount_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=3444, upload_to='images/'),
            preserve_default=False,
        ),
    ]
